spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway-demo
    username: ${db.appUser:admin}
    password: ${db.password:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true